// The assistant chat surface — hosted by the /venue/[placeId]/assistant
// modal route. Reuses useWsChat from P1 unchanged. Action cards
// (offer_slots / booking_confirmed / booking_failed) render inline; chat
// bubbles never carry them.
//
// envelope: [biz:<placeId> agent:<vertical_default>] <user text>
// Same shape web Atlas sends.
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Keyboard, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import BottomSheet, { BottomSheetView } from "@gorhom/bottom-sheet";
import { ArrowUp, Calendar, Check, X } from "lucide-react-native";

import { useWsChat, type TimelineItem } from "@/features/chat/useWsChat";
import { deriveAction, type ChatAction } from "@/features/chat/actions";
import { scopedEnvelope } from "@/features/chat/envelope";
import { env } from "@/lib/env";
import { metaFor } from "@web/places/verticals";
import type { Business } from "@web/places/types";
import type { AgentSlug } from "@web/agents/registry";

const BRAND_VIOLET = "#A672E0";

interface Props {
  business: Business;
  userId: string;
  /** Generated by the parent route on each open — keeps each sheet
   *  invocation its own ConversationWorkflow. */
  sessionId: string;
  userLoc?: { lat: number; lng: number } | null;
}

export function AssistantSheet({ business, userId, sessionId, userLoc }: Props) {
  const tenantId = env.defaultTenant;
  const agentSlug: AgentSlug = metaFor(business.vertical).defaultAgent;

  const sheetRef = useRef<BottomSheet>(null);
  const snapPoints = useMemo(() => ["50%", "90%"], []);

  // Keyboard ↔ sheet sync — RN's keyboardBehavior on iOS handles input
  // position; we just bump the snap so chat bubbles stay visible.
  useEffect(() => {
    const showSub = Keyboard.addListener("keyboardDidShow", () => sheetRef.current?.snapToIndex(1));
    const hideSub = Keyboard.addListener("keyboardDidHide", () => sheetRef.current?.snapToIndex(0));
    return () => {
      showSub.remove();
      hideSub.remove();
    };
  }, []);

  const { status, items, send } = useWsChat({ tenantId, sessionId, userId });
  const action: ChatAction = useMemo(() => deriveAction(items), [items]);

  const [draft, setDraft] = useState("");

  const sendEnvelope = useCallback(
    (text: string) => {
      const env_ = scopedEnvelope(text, { placeId: business.place_id, agent: agentSlug, userLoc });
      send(env_);
    },
    [business.place_id, agentSlug, userLoc, send],
  );

  const onSubmit = () => {
    const t = draft.trim();
    if (!t) return;
    sendEnvelope(t);
    setDraft("");
  };

  const onPickSlot = (slot: string) => {
    sendEnvelope(`yes book ${slot}`);
  };

  const onOpenBooking = (bookingId: string) => {
    router.replace({
      pathname: "/venue/[placeId]/book/confirm",
      params: { placeId: business.place_id, booking_id: bookingId },
    });
  };

  return (
    <View className="flex-1">
      {/* Tap-out backdrop */}
      <Pressable className="flex-1 bg-black/40" onPress={() => router.back()} />

      <BottomSheet
        ref={sheetRef}
        snapPoints={snapPoints}
        index={0}
        enablePanDownToClose
        onClose={() => router.back()}
        backgroundStyle={{ backgroundColor: "#FFFFFF" }}
        handleIndicatorStyle={{ backgroundColor: "#B6AE96" }}
        keyboardBehavior="interactive"
        keyboardBlurBehavior="restore"
      >
        <BottomSheetView style={{ flex: 1 }}>
          <Header
            venueName={business.display_name}
            statusLabel={statusLabel(status)}
            onClose={() => router.back()}
          />

          <ScrollView
            className="flex-1 px-4"
            contentContainerStyle={{ paddingBottom: 12 }}
            keyboardShouldPersistTaps="handled"
          >
            {items.length === 0 ? (
              <EmptyHint agent={agentSlug} />
            ) : (
              items.map((it, i) => <TimelineBubble key={i} item={it} />)
            )}
          </ScrollView>

          {action ? (
            <ActionStrip action={action} onPickSlot={onPickSlot} onOpenBooking={onOpenBooking} />
          ) : null}

          <View className="flex-row items-center px-3 pt-2 pb-3 border-t border-paper-500/60">
            <TextInput
              value={draft}
              onChangeText={setDraft}
              placeholder="Ask anything — slots, prices, advice…"
              placeholderTextColor="#9A968C"
              returnKeyType="send"
              onSubmitEditing={onSubmit}
              className="flex-1 bg-paper-100 rounded-2xl px-3 py-2 text-ink-800 text-sm"
            />
            <Pressable
              onPress={onSubmit}
              className="w-10 h-10 rounded-full bg-ink-800 items-center justify-center ml-2"
              accessibilityRole="button"
              accessibilityLabel="Send"
            >
              <ArrowUp size={16} color="#FBF7EE" />
            </Pressable>
          </View>
        </BottomSheetView>
      </BottomSheet>
    </View>
  );
}

// ─────────────────────────── pieces ───────────────────────────

function statusLabel(s: ReturnType<typeof useWsChat>["status"]): string {
  switch (s) {
    case "connected": return "Connected";
    case "connecting": return "Connecting…";
    case "closed": return "Disconnected";
    case "error": return "Connection error";
    default: return "Idle";
  }
}

function Header({
  venueName,
  statusLabel,
  onClose,
}: {
  venueName: string;
  statusLabel: string;
  onClose: () => void;
}) {
  return (
    <View className="flex-row items-center justify-between px-4 pt-2 pb-3 border-b border-paper-500/60">
      <View className="flex-1 pr-3">
        <Text className="text-ink-800 text-base font-semibold" numberOfLines={1}>
          Ask about {venueName}
        </Text>
        <Text className="text-ink-200 text-xs mt-0.5">{statusLabel}</Text>
      </View>
      <Pressable onPress={onClose} className="w-8 h-8 items-center justify-center">
        <X size={20} color="#3A3A36" />
      </Pressable>
    </View>
  );
}

function EmptyHint({ agent }: { agent: AgentSlug }) {
  return (
    <View className="py-6">
      <Text className="text-ink-200 text-sm">
        Connected to the <Text className="text-ink-800 font-medium">{agent}</Text> agent.
        Try “any openings tomorrow?” or “what does an appointment cost?”
      </Text>
    </View>
  );
}

function TimelineBubble({ item }: { item: TimelineItem }) {
  if (item.kind === "user") {
    return (
      <View className="self-end my-1 max-w-[80%]">
        <View className="bg-ink-800 px-3 py-2 rounded-2xl">
          <Text className="text-paper-100 text-sm">{item.text}</Text>
        </View>
      </View>
    );
  }
  const r = item.reply;
  if (r.role === "system") {
    return (
      <Text className="text-ink-200 text-xs italic my-1">
        {String((r.content as { text?: string }).text ?? "")}
      </Text>
    );
  }
  if (r.role !== "say") return null;
  const text = String((r.content as { text?: string }).text ?? "");
  return (
    <View className="self-start my-1 max-w-[85%]">
      <View className="bg-paper-200 px-3 py-2 rounded-2xl">
        <Text className="text-ink-800 text-sm">{text}</Text>
      </View>
    </View>
  );
}

function ActionStrip({
  action,
  onPickSlot,
  onOpenBooking,
}: {
  action: NonNullable<ChatAction>;
  onPickSlot: (slot: string) => void;
  onOpenBooking: (bookingId: string) => void;
}) {
  if (action.kind === "offer_slots") {
    return (
      <View className="px-3 py-2 border-t border-paper-500/60 bg-paper-100">
        <Text className="text-ink-500 text-xs uppercase tracking-wider mb-2">
          Suggested times
        </Text>
        <View className="flex-row flex-wrap">
          {action.slots.map((s) => (
            <Pressable
              key={s}
              onPress={() => onPickSlot(s)}
              style={{ backgroundColor: BRAND_VIOLET }}
              className="px-3 py-2 rounded-xl mr-2 mb-2"
            >
              <Text className="text-white text-sm font-medium">{s}</Text>
            </Pressable>
          ))}
        </View>
      </View>
    );
  }
  if (action.kind === "booking_confirmed") {
    return (
      <View className="px-3 py-3 border-t border-paper-500/60 bg-paper-100">
        <View className="flex-row items-center gap-2 mb-2">
          <Check size={16} color={BRAND_VIOLET} />
          <Text className="text-ink-800 text-sm font-semibold">
            Booked at {action.business_name} · {action.slot}
          </Text>
        </View>
        <Pressable
          onPress={() => onOpenBooking(action.booking_id)}
          className="flex-row items-center justify-center gap-2 bg-ink-800 rounded-2xl py-3"
        >
          <Calendar size={14} color="#FBF7EE" />
          <Text className="text-paper-100 text-sm font-semibold">Open booking</Text>
        </Pressable>
      </View>
    );
  }
  if (action.kind === "booking_failed") {
    return (
      <View className="px-3 py-3 border-t border-paper-500/60 bg-paper-100">
        <Text className="text-rust-500 text-sm font-medium">
          Couldn’t book — {action.reason}
        </Text>
      </View>
    );
  }
  return null;
}
