#!/usr/bin/env node
/**
 * sync-openapi.mjs — fetch /openapi.json from the FastAPI surface and
 * generate src/lib/api/schema.ts via openapi-typescript.
 *
 * Reads EXPO_PUBLIC_API_BASE from .env.development. Stop and flag (not
 * a stub fallback) if the tunnel is down — per HDGEcalls lesson.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ENV = resolve(HERE, "../.env.development");
const OUT = resolve(HERE, "../src/lib/api/schema.ts");

let apiBase = process.env.EXPO_PUBLIC_API_BASE;
if (!apiBase) {
  try {
    const env = readFileSync(ENV, "utf8");
    const m = env.match(/^EXPO_PUBLIC_API_BASE\s*=\s*(.+)$/m);
    if (m) apiBase = m[1].trim();
  } catch {
    // fall through to error below
  }
}
if (!apiBase) {
  console.error("sync-openapi: no EXPO_PUBLIC_API_BASE in env or .env.development");
  process.exit(1);
}

const url = `${apiBase.replace(/\/$/, "")}/openapi.json`;
console.log(`sync-openapi: fetching ${url}`);

try {
  execFileSync(
    "npx",
    ["openapi-typescript", url, "-o", OUT],
    { stdio: "inherit" },
  );
} catch (err) {
  console.error("sync-openapi: failed — is the cloudflared tunnel up?");
  process.exit(1);
}

writeFileSync(
  OUT,
  "// AUTO-GENERATED by scripts/sync-openapi.mjs — do not hand-edit.\n" +
    readFileSync(OUT, "utf8"),
);
console.log(`sync-openapi: wrote ${OUT}`);
