#!/usr/bin/env node
/**
 * sync-tokens.mjs — read the canonical tokens from
 * plnt-cloud/web/src/styles/tokens.css and emit a typed JS module at
 * mobile/src/styles/tokens.js (+ a .d.ts companion) that the
 * tailwind.config.js consumes and RN code can import at runtime.
 *
 * We don't depend on PostCSS to keep this script zero-install — just a
 * focused regex over the `:root { --token: value; }` block.
 *
 * Run after touching web/src/styles/tokens.css:
 *   npm run tokens:sync
 *
 * The mobile-only `theme.extend.colors` shape in tailwind.config.js is:
 *   paper: { 50: "#…", 100: "#…", … }
 *   ink:   { 50: "#…", … }
 *   ...
 *
 * Anything that isn't a color/space/radius is exported under `raw` for
 * direct lookup. The web's hand-translated legacy aliases at the bottom
 * of tokens.css are skipped.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(HERE, "../../web/src/styles/tokens.css");
const OUT_JS = resolve(HERE, "../src/styles/tokens.js");
const OUT_DTS = resolve(HERE, "../src/styles/tokens.d.ts");

const css = readFileSync(SRC, "utf8");
const rootMatch = css.match(/:root\s*\{([\s\S]*?)\}/);
if (!rootMatch) {
  console.error("sync-tokens: could not find :root { ... } in tokens.css");
  process.exit(1);
}
const body = rootMatch[1];

const pairs = [];
for (const line of body.split("\n")) {
  const m = line.match(/^\s*(--[a-zA-Z0-9-]+)\s*:\s*([^;]+);/);
  if (!m) continue;
  pairs.push([m[1], m[2].trim()]);
}

// Resolve `var(--x)` references one level deep — enough for the legacy
// aliases at the bottom of tokens.css.
const byKey = new Map(pairs);
function resolveValue(v) {
  const m = /^var\((--[a-zA-Z0-9-]+)\)$/.exec(v);
  if (!m) return v;
  return byKey.get(m[1]) ?? v;
}

const colors = {};      // family -> {scale: value}
const space = {};
const radius = {};
const motion = {};
const raw = {};

const COLOR_FAMILIES = new Set([
  "paper",
  "ink",
  "coal",
  "sage",
  "amber",
  "rust",
  "sky",
  "map",
  "iri",
]);

for (const [k, vRaw] of pairs) {
  const v = resolveValue(vRaw);
  let m;
  if ((m = /^--color-([a-z]+)-([a-z0-9]+)$/.exec(k))) {
    const family = m[1];
    const scale = m[2];
    if (!COLOR_FAMILIES.has(family)) {
      raw[k.slice(2)] = v;
      continue;
    }
    (colors[family] ||= {})[scale] = v;
  } else if ((m = /^--space-([0-9]+)$/.exec(k))) {
    // Tailwind uses unitless * 4px stops; we keep the literal px so
    // padding/m utilities map 1:1 to the design grid.
    space[m[1]] = v;
  } else if ((m = /^--radius-([a-z0-9-]+)$/.exec(k))) {
    radius[m[1]] = v;
  } else if ((m = /^--motion-([a-z0-9-]+)$/.exec(k))) {
    motion[m[1]] = v;
  } else {
    raw[k.slice(2)] = v;
  }
}

// Tailwind expects color objects keyed by string. Keep scale keys as strings.
const out = {
  colors,
  space,
  radius,
  motion,
  raw,
};

mkdirSync(dirname(OUT_JS), { recursive: true });

const header =
  "// AUTO-GENERATED by scripts/sync-tokens.mjs — do not hand-edit.\n" +
  "// Source: plnt-cloud/web/src/styles/tokens.css\n";

writeFileSync(
  OUT_JS,
  header + "module.exports = " + JSON.stringify(out, null, 2) + ";\n",
);

const dts = [
  "// AUTO-GENERATED by scripts/sync-tokens.mjs",
  "declare const tokens: {",
  "  colors: Record<string, Record<string, string>>;",
  "  space: Record<string, string>;",
  "  radius: Record<string, string>;",
  "  motion: Record<string, string>;",
  "  raw: Record<string, string>;",
  "};",
  "export = tokens;",
  "",
].join("\n");
writeFileSync(OUT_DTS, dts);

console.log(
  `sync-tokens: wrote ${Object.keys(colors).length} color families, ` +
    `${Object.keys(space).length} spaces, ${Object.keys(radius).length} radii ` +
    `→ ${OUT_JS}`,
);
