// AUTO-GENERATED by scripts/sync-tokens.mjs
declare const tokens: {
  colors: Record<string, Record<string, string>>;
  space: Record<string, string>;
  radius: Record<string, string>;
  motion: Record<string, string>;
  raw: Record<string, string>;
};
export = tokens;
