// AUTO-GENERATED by scripts/sync-tokens.mjs — do not hand-edit.
// Source: plnt-cloud/web/src/styles/tokens.css
module.exports = {
  "colors": {
    "paper": {
      "50": "#FFFCF4",
      "100": "#FBF7EE",
      "200": "#F8F2E0",
      "300": "#F4EEDF",
      "400": "#F1ECDC",
      "500": "#E4DCC6",
      "600": "#D8CFB4",
      "700": "#B6AE96",
      "800": "#8A8472",
      "900": "#5F5B4E"
    },
    "ink": {
      "50": "#6C6A60",
      "100": "#9A968C",
      "200": "#6C6A60",
      "300": "#5A584F",
      "400": "#4A4843",
      "500": "#3A3A36",
      "600": "#2A2A28",
      "700": "#1C1E22",
      "800": "#0E1116",
      "900": "#07090C"
    },
    "coal": {
      "50": "#D6D2C4",
      "100": "#BCB8AB",
      "200": "#7A786E",
      "300": "#4F4E47",
      "400": "#34353B",
      "500": "#23262C",
      "600": "#15171B",
      "700": "#0A0B0D",
      "800": "#06070A",
      "900": "#030405"
    },
    "sage": {
      "500": "#5E8B5E"
    },
    "amber": {
      "500": "#C97B2A"
    },
    "rust": {
      "500": "#B5572E"
    },
    "sky": {
      "500": "#3B6EA8"
    },
    "iri": {
      "blue": "#1A73E8",
      "violet": "#A672E0",
      "rose": "#E26478"
    },
    "map": {
      "land": "#F1ECDC",
      "park": "#CFE0B0",
      "water": "#A6CFE3",
      "road": "#FFFAEC"
    }
  },
  "space": {
    "0": "0",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px",
    "12": "48px",
    "16": "64px",
    "20": "80px"
  },
  "radius": {
    "xs": "4px",
    "sm": "8px",
    "md": "12px",
    "lg": "16px",
    "xl": "20px",
    "pill": "999px",
    "input": "12px",
    "card": "16px",
    "tile": "12px"
  },
  "motion": {
    "fast": "140ms",
    "base": "200ms",
    "slow": "320ms",
    "slower": "480ms"
  },
  "raw": {
    "gradient-iri": "linear-gradient(135deg, #1A73E8 0%, #6A8DE0 28%, #A672E0 58%, #E26478 100%)",
    "gradient-iri-soft": "linear-gradient(135deg, rgba(26,115,232,0.10), rgba(166,114,224,0.10) 55%, rgba(226,100,120,0.10))",
    "color-map-road-dim": "#F5EFDC",
    "shadow-xs": "0 1px 2px rgba(14,17,22,0.04)",
    "shadow-sm": "0 1px 2px rgba(14,17,22,0.04), 0 2px 6px rgba(14,17,22,0.06)",
    "shadow-md": "0 1px 2px rgba(14,17,22,0.04), 0 8px 24px rgba(14,17,22,0.08)",
    "shadow-lg": "0 2px 6px rgba(14,17,22,0.05), 0 24px 64px rgba(14,17,22,0.14)",
    "shadow-float": "0 1px 2px rgba(14,17,22,0.04), 0 8px 24px rgba(14,17,22,0.08)",
    "shadow-deep": "0 2px 6px rgba(14,17,22,0.05), 0 24px 64px rgba(14,17,22,0.14)",
    "shadow-ring": "0 0 0 3px rgba(26,115,232,0.18)",
    "ease-out": "cubic-bezier(0.2, 0.7, 0.3, 1)",
    "ease-in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
    "ease-spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
    "sidebar-w": "340px",
    "chat-w": "400px",
    "nav-h": "64px",
    "font-sans": "\"Geist Variable\", \"Geist\", Inter, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif",
    "font-mono": "\"JetBrains Mono\", ui-monospace, SFMono-Regular, Menlo, monospace",
    "paper": "#FBF7EE",
    "paper-deep": "#F4EEDF",
    "paper-warm": "#F8F2E0",
    "surface": "#FFFFFF",
    "surface-2": "#F7F4EC",
    "ink": "#0E1116",
    "ink-soft": "#3A3A36",
    "ink-mute": "#6C6A60",
    "ink-faint": "#9A968C",
    "hairline": "#E4DCC6",
    "hairline-2": "#D8CFB4",
    "sage": "#5E8B5E",
    "amber": "#C97B2A",
    "rust": "#B5572E",
    "sky": "#3B6EA8",
    "map-land": "#F1ECDC",
    "map-park": "#CFE0B0",
    "map-water": "#A6CFE3",
    "map-road": "#FFFAEC",
    "map-road-dim": "#F5EFDC",
    "iri-blue": "#1A73E8",
    "iri-violet": "#A672E0",
    "iri-rose": "#E26478",
    "iridescent": "linear-gradient(135deg, #1A73E8 0%, #6A8DE0 28%, #A672E0 58%, #E26478 100%)",
    "iridescent-soft": "linear-gradient(135deg, rgba(26,115,232,0.10), rgba(166,114,224,0.10) 55%, rgba(226,100,120,0.10))",
    "coal": "#0A0B0D",
    "coal-soft": "#15171B",
    "coal-line": "#23262C",
    "coal-text": "#D6D2C4",
    "coal-mute": "#7A786E",
    "coal-mute-2": "#4F4E47"
  }
};
