"""Runtime backends for the playground API.

`RuntimeAdapter` is the abstraction across inference backends. Concrete
implementations:

* `MockBackend` — deterministic echo, useful on kind (no GPU) and in tests.
* `HTTPBackend` — proxies to any upstream that speaks OpenAI /v1/chat/completions
  (vLLM, TGI --openai-compat, SGLang, and llama.cpp server all do). This is what
  the vllm-runtime Helm chart will register once it lands.
"""

from __future__ import annotations

import json
import time
import uuid
from collections.abc import AsyncIterator
from typing import Protocol

import httpx

from plnt.playground.schemas import (
    ChatCompletionChoice,
    ChatCompletionChunk,
    ChatCompletionChunkChoice,
    ChatCompletionDelta,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatCompletionUsage,
    ChatMessage,
)


class RuntimeAdapter(Protocol):
    model_id: str
    runtime: str

    async def complete(self, req: ChatCompletionRequest) -> ChatCompletionResponse: ...

    def stream(self, req: ChatCompletionRequest) -> AsyncIterator[ChatCompletionChunk]: ...


def _now() -> int:
    return int(time.time())


def _id() -> str:
    return f"chatcmpl-{uuid.uuid4().hex[:24]}"


def _approx_tokens(text: str) -> int:
    return max(1, len(text) // 4)


class MockBackend:
    """Echoes the last user message word-by-word. No GPU, no network, no vibes."""

    def __init__(self, model_id: str, runtime: str = "mock") -> None:
        self.model_id = model_id
        self.runtime = runtime

    def _reply_text(self, req: ChatCompletionRequest) -> str:
        last_user = next(
            (m.content for m in reversed(req.messages) if m.role == "user"),
            "",
        )
        preview = last_user.strip() or "(empty prompt)"
        return (
            f"[mock:{self.model_id}] You said: {preview}. "
            "This response is generated by the playground's mock backend — "
            "swap the runtime to a real vLLM pod to get actual inference."
        )

    async def complete(self, req: ChatCompletionRequest) -> ChatCompletionResponse:
        text = self._reply_text(req)
        prompt_tokens = sum(_approx_tokens(m.content) for m in req.messages)
        completion_tokens = _approx_tokens(text)
        return ChatCompletionResponse(
            id=_id(),
            created=_now(),
            model=self.model_id,
            choices=[
                ChatCompletionChoice(
                    index=0,
                    message=ChatMessage(role="assistant", content=text),
                    finish_reason="stop",
                )
            ],
            usage=ChatCompletionUsage(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=prompt_tokens + completion_tokens,
            ),
        )

    async def stream(self, req: ChatCompletionRequest) -> AsyncIterator[ChatCompletionChunk]:
        text = self._reply_text(req)
        cid = _id()
        created = _now()

        yield ChatCompletionChunk(
            id=cid,
            created=created,
            model=self.model_id,
            choices=[
                ChatCompletionChunkChoice(
                    index=0, delta=ChatCompletionDelta(role="assistant")
                )
            ],
        )

        for word in text.split(" "):
            yield ChatCompletionChunk(
                id=cid,
                created=created,
                model=self.model_id,
                choices=[
                    ChatCompletionChunkChoice(
                        index=0, delta=ChatCompletionDelta(content=word + " ")
                    )
                ],
            )

        yield ChatCompletionChunk(
            id=cid,
            created=created,
            model=self.model_id,
            choices=[
                ChatCompletionChunkChoice(
                    index=0, delta=ChatCompletionDelta(), finish_reason="stop"
                )
            ],
        )


class HTTPBackend:
    """Proxies to an upstream OpenAI-compatible /v1/chat/completions endpoint.

    Uses the caller-supplied model name at the wire level so a single upstream
    can serve multiple aliases if configured that way.
    """

    def __init__(
        self,
        model_id: str,
        upstream_url: str,
        runtime: str = "vllm",
        upstream_model: str | None = None,
        api_key: str | None = None,
        timeout_seconds: float = 60.0,
    ) -> None:
        self.model_id = model_id
        self.runtime = runtime
        self.upstream_url = upstream_url.rstrip("/")
        self.upstream_model = upstream_model or model_id
        self.api_key = api_key
        self.timeout_seconds = timeout_seconds

    def _headers(self) -> dict[str, str]:
        h = {"content-type": "application/json"}
        if self.api_key:
            h["authorization"] = f"Bearer {self.api_key}"
        return h

    def _payload(self, req: ChatCompletionRequest, stream: bool) -> dict:
        return {
            "model": self.upstream_model,
            "messages": [m.model_dump() for m in req.messages],
            "stream": stream,
            "max_tokens": req.max_tokens,
            "temperature": req.temperature,
            "top_p": req.top_p,
        }

    async def complete(self, req: ChatCompletionRequest) -> ChatCompletionResponse:
        async with httpx.AsyncClient(timeout=self.timeout_seconds) as client:
            resp = await client.post(
                f"{self.upstream_url}/v1/chat/completions",
                json=self._payload(req, stream=False),
                headers=self._headers(),
            )
            resp.raise_for_status()
            data = resp.json()
        data["model"] = self.model_id
        return ChatCompletionResponse.model_validate(data)

    async def stream(self, req: ChatCompletionRequest) -> AsyncIterator[ChatCompletionChunk]:
        async with httpx.AsyncClient(timeout=self.timeout_seconds) as client:
            async with client.stream(
                "POST",
                f"{self.upstream_url}/v1/chat/completions",
                json=self._payload(req, stream=True),
                headers=self._headers(),
            ) as resp:
                resp.raise_for_status()
                async for line in resp.aiter_lines():
                    if not line or not line.startswith("data:"):
                        continue
                    payload = line[len("data:") :].strip()
                    if payload == "[DONE]":
                        return
                    try:
                        chunk_data = json.loads(payload)
                    except json.JSONDecodeError:
                        continue
                    chunk_data["model"] = self.model_id
                    yield ChatCompletionChunk.model_validate(chunk_data)
